apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-service
  namespace: hypothesis-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-service
  template:
    metadata:
      labels:
        app: prefect-service
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: prefect-service
          image: abdum1964/hypothesis-generation-prefect-service:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 4200
          env:
            - name: PREFECT_API_URL
              value: "http://prefect-service:4200/api"
            - name: PREFECT_UI_API_URL
              value: "https://dev.rejuve.bio:5054/api"
            - name: UV_PROJECT_ENVIRONMENT
              value: "/opt/prefect-venv"
            - name: DASK_ADDRESS
              value: "tcp://dask-scheduler:8786"
            - name: PREFECT_API_DATABASE_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  name: hypothesis-secrets
                  key: PREFECT_API_DATABASE_CONNECTION_URL
          envFrom:
            - secretRef:
                name: hypothesis-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: prefect-service
  namespace: hypothesis-staging
spec:
  selector:
    app: prefect-service
  ports:
    - port: 4200
      targetPort: 4200
